---
title: "project_ideas_Yan"
author: "Yan Wang"
date: "11/10/2021"
output: 
  github_document: 
    toc: TRUE
---
# Idea 

## Working title

Linguistic reflections of perceived symptom controllability among women
with recurrent ovarian cancer

## Summary

This is the final project idea for Data Science for Linguists (LING
2340). The purpose is to explore the linguistic remarks of patients
perceived control over their symptoms for women with recurrent ovarian cancer

## Data portion

WRITE Symptoms (Written Representational Intervention To Ease Symptoms)
was a three-arm randomized clinical trial that improves symptom
management and life quality for women with recurrent ovarian cancer. In
the self-directed arm of WRITE (SD WRITE), the intervention emphasizes
a detailed assessment of patients’ symptom (e.g., pain, fatigue) beliefs
to provide relevant and specific symptom management recommendations that
facilitate patient learning and behavior change. Participants select their own goals and strategies to manage symptoms. All participants' symptom representation posts were recorded verbatim on the website. 

## Aanalysis portion

I want to (1) develop a list of linguistic features for patient
perceived controllability based on content expertise and the literature, (2) use linear mixed-effects model to predict symptom
controllability using linguistic features
